apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-c16c04a0-18d3-41bf-bb07-79efaa39462d
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  annotations:
    ngrok.com/ingress-mode: edge
  labels:
    app: springboot-app-c16c04a0-18d3-41bf-bb07-79efaa39462d
spec:
  ingressClassName: nginx
  rules:
    - host: picked-apt-wombat.ngrok-free.app
      http:
        paths:
          - backend:
              service:
                name: springboot-service-c16c04a0-18d3-41bf-bb07-79efaa39462d
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-c16c04a0-18d3-41bf-bb07-79efaa39462d
                port:
                  number: 80
            path: /graphql
            pathType: Prefix
