apiVersion: v1
kind: Service
metadata:
  name: springboot-service-6a8424e9-e82a-43bb-bc76-5873d6e0e1ab
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
spec:
  selector:
    app: springboot-app-6a8424e9-e82a-43bb-bc76-5873d6e0e1ab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

