apiVersion: v1
kind: Service
metadata:
  name: springboot-service-3fbcd35a-ceca-4f81-a80f-78063c3af47e
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  selector:
    app: springboot-app-3fbcd35a-ceca-4f81-a80f-78063c3af47e
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

