apiVersion: v1
kind: Service
metadata:
  name: springboot-service-bd1780bb-5416-460f-b58c-9c42d80d977b
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  selector:
    app: springboot-app-bd1780bb-5416-460f-b58c-9c42d80d977b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

