apiVersion: v1
kind: Service
metadata:
  name: springboot-service-d5852e2d-5fbd-4932-a766-9271a3553d53
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  selector:
    app: springboot-app-d5852e2d-5fbd-4932-a766-9271a3553d53
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

