apiVersion: v1
kind: Service
metadata:
  name: springboot-service-6dbc7ebc-f3a3-4044-8dd3-4a5f5291a1a6
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
spec:
  selector:
    app: springboot-app-6dbc7ebc-f3a3-4044-8dd3-4a5f5291a1a6
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

