apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-c46e27ea-e228-41c8-a1e2-f51e957ae3e8
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  annotations:
    ngrok.com/ingress-mode: edge
  labels:
    app: springboot-app-c46e27ea-e228-41c8-a1e2-f51e957ae3e8
spec:
  ingressClassName: nginx
  rules:
    - host: picked-apt-wombat.ngrok-free.app
      http:
        paths:
          - backend:
              service:
                name: springboot-service-c46e27ea-e228-41c8-a1e2-f51e957ae3e8
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-c46e27ea-e228-41c8-a1e2-f51e957ae3e8
                port:
                  number: 80
            path: /graphql
            pathType: Prefix
