apiVersion: v1
kind: Service
metadata:
  name: springboot-service-493b8c20-3d5f-440b-97eb-3997b9a7e105
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
spec:
  selector:
    app: springboot-app-493b8c20-3d5f-440b-97eb-3997b9a7e105
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

