apiVersion: v1
kind: Service
metadata:
  name: springboot-service-ff32a373-40ea-4014-bb98-ea2d789f3c9c
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
spec:
  selector:
    app: springboot-app-ff32a373-40ea-4014-bb98-ea2d789f3c9c
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

