apiVersion: v1
kind: Service
metadata:
  name: springboot-service-a44cc2ed-4fbb-4a74-86a9-2296e99744b6
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  selector:
    app: springboot-app-a44cc2ed-4fbb-4a74-86a9-2296e99744b6
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

