apiVersion: v1
kind: Service
metadata:
  name: springboot-service-a53fa300-7190-4851-8bc1-e156470b59db
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  selector:
    app: springboot-app-a53fa300-7190-4851-8bc1-e156470b59db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

