apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-630af869-856a-4261-9a9a-4066c9c15d85
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  labels:
    app: springboot-app-630af869-856a-4261-9a9a-4066c9c15d85
spec:
  ingressClassName: nginx
  rules:
    - host: app-l8qg6w.mo09zm.us-east-2.febe.k8s
      http:
        paths:
          - backend:
              service:
                name: springboot-service-630af869-856a-4261-9a9a-4066c9c15d85
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-630af869-856a-4261-9a9a-4066c9c15d85
                port:
                  number: 80
            path: /graphql
            pathType: Prefix