apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-048bf318-a488-444d-b504-e7444e941314
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  annotations:
    ngrok.com/ingress-mode: edge
  labels:
    app: springboot-app-048bf318-a488-444d-b504-e7444e941314
spec:
  ingressClassName: ngrok
  rules:
    - host: picked-apt-wombat.ngrok-free.app
      http:
        paths:
          - backend:
              service:
                name: springboot-service-048bf318-a488-444d-b504-e7444e941314
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-048bf318-a488-444d-b504-e7444e941314
                port:
                  number: 80
            path: /graphql
            pathType: Prefix