apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-0456e7b5-eb4e-4970-a00d-6d85aecf55be
  namespace: 3219e62e-f28c-4e9a-b62e-77aae69fb44b
  annotations:
    ngrok.com/ingress-mode: edge
  labels:
    app: springboot-app-0456e7b5-eb4e-4970-a00d-6d85aecf55be
spec:
  ingressClassName: nginx
  rules:
    - host: picked-apt-wombat.ngrok-free.app
      http:
        paths:
          - backend:
              service:
                name: springboot-service-0456e7b5-eb4e-4970-a00d-6d85aecf55be
                port:
                  number: 80
            path: /graphiql
            pathType: Prefix
          - backend:
              service:
                name: springboot-service-0456e7b5-eb4e-4970-a00d-6d85aecf55be
                port:
                  number: 80
            path: /graphql
            pathType: Prefix
