apiVersion: v1
kind: Service
metadata:
  name: springboot-service-306bbf55-4579-44a3-8c31-d7b296a25bc9
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  selector:
    app: springboot-app-306bbf55-4579-44a3-8c31-d7b296a25bc9
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

