apiVersion: v1
kind: Service
metadata:
  name: springboot-service-825c87fd-3f76-4865-bdf7-f4a989a45d6c
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  selector:
    app: springboot-app-825c87fd-3f76-4865-bdf7-f4a989a45d6c
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

