apiVersion: v1
kind: Service
metadata:
  name: springboot-service-3cede942-2cd8-44a7-84fc-128169f9df7d
  namespace: 2e49f282-85d5-4866-af7d-8133a75e6769
spec:
  selector:
    app: springboot-app-3cede942-2cd8-44a7-84fc-128169f9df7d
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP

